version: "3.9"

services:

  api:
    build: .
    container_name: ml-monitor-api
    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres
      - redis



  worker:
    build: .
    container_name: celery-worker
    restart: unless-stopped

    command: celery -A app.core.celery worker --loglevel=info

    env_file:
      - .env

    depends_on:
      - redis
      - postgres



  postgres:
    image: postgres:16

    container_name: postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ml_monitor

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

    container_name: redis

    restart: always


volumes:
  postgres_data: